- name: Deploy to EC2
  host: localhost
  connection: local

  tasks:
    - name: Launch EC2 instance
      ec2:
        instance_type: t2.micro
        image: ami-04902260ca3d33422
        region: us-east-1
        key_name: devops
        vpc_subnet_id: subnet-0cadac1ea9d269fbc
        assign_public_ip: yes
        count: 1
        aws_access_key: "{{ access_key }}"
        aws_security_token: "{{ secret_key }}"
        security_token: "{{ session_token }}"